//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice3Task
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class ClientService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public System.DateTime ServiceTime { get; set; }
        public int ClientId { get; set; }
        public TimeSpan timeToStart { get; set; }
        public SolidColorBrush Foreground { get; set; }
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
